### ISSUE TITLE
Way to keep request forever?

### ISSUE THREAD

**Issue by ITCMD** [mxcxvn/requestbin.net#3]
I'm locally hosting this tool through docker and I was wondering if there was a way to keep request bins forever instead of for the last 48 hours?

**Comment by chung1905** [comment]
I believe you can find it here:
https://github.com/mxcxvn/requestbin.net/blob/master/web/requestbin/config.py

**Comment by cuongmx** [comment]
Now, it's supported on new version, check it at https://requestbin.net
