### ISSUE TITLE
DNSBin is broken

### ISSUE THREAD

**Issue by CherryDT** [mxcxvn/requestbin.net#6]
Trying to use the DNSBin just shows an empty page, and the devtools show errors in the websocket connection. Tried from 2 different browsers and IPs.

```
dns:34 WebSocket connection to 'wss://dns.requestbin.net:8443/dnsbin' failed: Error during WebSocket handshake: Unexpected response code: 521
createSocket @ dns:34
04:02:50.983 dns:112 Uncaught TypeError: Cannot read property 'appendChild' of null
    at WebSocket.socketConnection.onclose (dns:112)
```

**Comment by eudalov** [comment]
Hi! Any update on this?

**Comment by cyberbharathi** [comment]
Hello, @mxcxvn Still this source code and website are broken in dns functionality!

**Comment by cuongmx** [comment]
Sorry about that, we have some issue in the resource. Now, it's seem be better. Please check status at https://status.requestbin.net/
